Resources:
  OrganizationLambdaTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sarapis.lambda.OrganizationHandlerLambda::handleRequest
      Runtime: java21
      CodeUri: ./
      Environment:
        Variables:
          ACCESS_KEY: FAKEID
          SECRET_KEY: FAKEKEY
      Events:
        Api:
          Type: Api
          Properties:
            Path: /organizations
            Method: GET
